# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companycd',
            field=models.CharField(default=datetime.datetime(2016, 2, 21, 8, 38, 19, 23161, tzinfo=utc), max_length=255, verbose_name='会社コード'),
            preserve_default=False,
        ),
    ]
